### ISSUE TITLE
binding.gyp contains "src/attribute.cc" line but there are no src/attribute.cc file

### ISSUE THREAD

**Issue by edy555** [jacklund/btle.js#13]
Hi Jack,
I just tried to build from source code, but unfortunately it was failed to build.

> $ make debug
> ...
> make[1]: **\* No rule to make target `Debug/obj.target/btle/src/attribute.o', needed by`Debug/obj.target/btle.node'.  Stop.
> make[1]: Leaving directory `/home/takahasi/btle.js/build'
> gyp ERR! build error 
> gyp ERR! stack Error:`make` failed with exit code: 2

It seems that binding.gyp contains "src/attribute.cc" line, but there are no 
attribute.cc file in src directory.

I tried to build with omit the line from binding.gyp, I got to succeed to build it.

If I have any mistake, please let me know.
Thanks for your efforts.
## 

TT @edy555

**Comment by jacklund** [comment]
Sorry, it was building for me because I had the object file still hanging around.

I've fixed the binding.gyp. Do a pull and rebuild, and you should be good to go.

Let me know if you have any more issues.

-Jack

**Comment by edy555** [comment]
Thank you for very quick fix. I pulled change and confirmed the problem was
fixed. Thank you!
