### ISSUE TITLE
Use btls.js from Noble

### ISSUE THREAD

**Issue by deadprogram** [jacklund/btle.js#17]
Hi, @jacklund 

Cool project, you've done a lot of work on this. Having a more Linux-friendly implementation of a BLE lib is really useful, I'm surprised more people have not taken notice.

In any case, we are thinking of using btls.js as the Linux implenentation within Noble https://github.com/sandeepmistry/noble. This would allow using Noble's good OSX implementation with what seems to be a more solid Linux implementation in your project.

Is this something that is interesting to you?

**Comment by jacklund** [comment]
I'm really sorry for not getting back to you - holidays + my new work situation being very busy.

I'd be happy to help out as much as I can. This sounds like a really interesting way to go. I actually looked at noble before writing mine, but I wanted it to run on Linux, specifically Raspberry Pi.
