### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by yasdfgr** [jacklund/btle.js#18]
I tryed to install btle.js on my Rasberry Pi with "npm install btle.js" and i get a lot of errors.
What goes wrong?

Fist part of sequence:

```
In file included from ../src/btleConnection.cc:4:0:
../src/btleConnection.h:12:40: error: expected class-name before ‘{’ token
../src/btleConnection.h:22:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/btleConnection.h:22:57: warning: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/btleConnection.h:23:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
```

**Comment by jacklund** [comment]
That's very strange. I just tried it on mine (although it's an old pi), and it worked.

What version of npm (`npm -version`) and debian (`cat /etc/debian_version`) are you running?

**Comment by yasdfgr** [comment]
I have **npm version 2.11.2** and **debian version 7.8**
